name: Publish Nightly Docker Image
on:
  push:
    paths-ignore:
      - '.github/workflows/build.yml'
      - '*.md'
      - 'LICENSE'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get build date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S %z')"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        TAG: nightly
      with:
        name: icyleafcn/subweb:${{ env.TAG }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: icyleafcn/subweb

